# Generated by Django 2.2.1 on 2019-07-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190628_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_view_contact_info', '查看联系方式'),)},
        ),
    ]
