# Generated by Django 2.2.1 on 2019-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_auto_20190701_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='etime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='stime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
