# Generated by Django 2.2.1 on 2019-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expertinfo_ebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertinfo',
            name='efee',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
