# Generated by Django 2.2.1 on 2019-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexp',
            options={'managed': True, 'ordering': ('-stime',)},
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='esex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=2),
        ),
    ]
