# Generated by Django 2.2.1 on 2019-07-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20190628_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertinfo',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='expertcomments',
            name='eid',
            field=models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='experts.ExpertInfo'),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='addtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='esex',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='eid',
            field=models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='experts.ExpertInfo'),
        ),
        migrations.AlterModelTable(
            name='expertcomments',
            table='expert_comments',
        ),
        migrations.AlterModelTable(
            name='expertinfo',
            table='expert_info',
        ),
        migrations.AlterModelTable(
            name='workexp',
            table='work_exp',
        ),
    ]
