# Generated by Django 2.2.1 on 2019-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_auto_20190701_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertinfo',
            options={'managed': True, 'ordering': ('-addtime',)},
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
